update west.yml to ncs 2.7.0
IRNAS/irnas-zephyr-template pull request #32
Opened 2024-08-19 14:42 UTC by vid553

# Description

Closes #

Related #

## Areas of interest for the reviewer

## Checklist

- [ ] My code follows the [style guidelines] as defined by IRNAS.
- [ ] I have performed a self-review of my code.
- [ ] My changes generate no new warnings.
- [ ] I added/updated source code documentation for all newly added or changed functions.
- [ ] I updated all customer-facing technical documentation.

Example strikeout: - [x] ~~I updated all customer-facing technical documentation.~~ - This PR
introduced only internal facing changes.

## After-review steps

- Reviewer can merge and delete the branch.
- I will merge PR by myself.

[style guidelines]:
  https://github.com/IRNAS/irnas-guidelines-docs/blob/main/docs/developer_guidelines.md

2024-08-19 14:42 UTC, vid553 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-zephyr-template/32?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#32** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-zephyr-template/32?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#31** <a href="https://app.graphite.dev/github/pr/IRNAS/irnas-zephyr-template/31?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @vid553 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-08-20 12:28 UTC, MarkoSagadin requested changes
Minor thing regarding the `custom_nrf52840` to `custom_nrf52840dk` name change.

The `custom_nrf52840` represents the old naming scheme that was used in the Zephyr versions, prior to 3.6.0, basically `<board name>_<used soc>_<extra qualifiers>`.

So, `custom` is the name of the board and the `nrf52840` is the soc. 
If we translate to the newer model, then the board name changes to `custom/nrf52840`, instead of `custom_nrf52840dk`.

Please correct this, I think such board name will make adoption of the new hardware model easier and more clear.

2024-08-20 12:28 UTC, MarkoSagadin commented on west.yml
Since reviewing tools don't work well enough I will comment on the whole file.

I double checked the both `name-allowlist`s and I found some missing modules. Also the existing modules weren't sorted alphabetically, so I also fixed that.

Allowlist for nrf-sdk:

```yml
          # Ignore NCS private repos, keep this list sorted alphabetically.
          # - ant
          # - azure-sdk-for-c
          # - bme68x
          # - bsec
          # - bsim
          # - cirrus
          # - cjson
          - cmock
          # - coremark
          # - dragoon
          # - find-my
          # - hostap
          # - matter
          - mbedtls # Required for nRF9160 and nRF7002 projects, can be disabled for others.
          - mcuboot
          # - memfault-firmware-sdk
          # - nrf-802154
          - nrfxlib
          # - oberon-psa-crypto # Required for WPA support
          # - openthread
          - psa-arch-tests
          - qcbor
          # - sidewalk
          # - soc-hwmv1
          # - suit-generator
          # - suit-processor
          - trusted-firmware-m
          # - wfa-qt-control-app
          # Ignore zephyr repo as it is added below manually
          # - zephyr
```


Allowlist for zephyr-sdk:

```yml
          # - acpica
          # - babblesim_base
          # - babblesim_ext_2G4_channel_NtNcable
          # - babblesim_ext_2G4_channel_multiatt
          # - babblesim_ext_2G4_device_WLAN_actmod
          # - babblesim_ext_2G4_device_burst_interferer
          # - babblesim_ext_2G4_device_playback
          # - babblesim_ext_2G4_libPhyComv1
          # - babblesim_ext_2G4_modem_BLE_simple
          # - babblesim_ext_2G4_modem_magic
          # - babblesim_ext_2G4_phy_v1
          # - babblesim_ext_libCryptov1
          # - bsim
          - cmsis
          # - cmsis-dsp
          # - cmsis-nn
          # - edtt
          - fatfs
          # - hal_altera
          # - hal_ambiq
          # - hal_atmel
          # - hal_espressif
          # - hal_ethos_u
          # - hal_gigadevice
          # - hal_infineon
          # - hal_intel
          # - hal_microchip
          - hal_nordic
          # - hal_nuvoton
          # - hal_nxp
          # - hal_openisa
          # - hal_quicklogic
          # - hal_renesas
          # - hal_rpi_pico
          # - hal_silabs
          - hal_st # Hal for ST's sensors, not for MCU's
          # - hal_stm32
          # - hal_telink
          # - hal_ti
          # - hal_wurthelektronik
          # - hal_xtensa
          - hostap
          # - liblc3
          # - libmetal
          # - littlefs
          # - loramac-node
          # - lvgl
          # - mbedtls
          # - mcuboot # Do not use this one, Nordic has it's own fork.
          # - mipi-sys-t
          # - net-tools
          - nrf_hw_models
          # - open-amp
          # - openthread
          # - percepio
          - picolibc
          - segger
          - tinycrypt
          # - trusted-firmware-a
          # - trusted-firmware-m
          # - uoscore-uedhoc
          - zcbor
```

Funny enough, TraceRecoredSource does not exist in the `nrf-sdk/west.yml`, but is referenced in the `zephyr-sdk/west.yml`, someone at Nordic forgot to remove it :)

2024-08-20 13:14 UTC, MarkoSagadin commented
> I have only ported the board to new model and did not rename it.

I see that I made a mistake, you are right, the board was named `custom_nrf52840dk`, before I assumed that it was named `custom_nrf52840` because of the changes in the boards README.md file (which were originally wrong).

Thank you for fixing that :)

> I have added another commit that renames the board to custom_board (nrf52840 qualifier is not needed in the name as it's added automatically, since this board only has a single SOC possible).

That is okay, I think that this is a good choice.

---

I consider this PR as done, just please squash the commits that contain the requested changes into the original two commits.

2024-08-20 13:15 UTC, MarkoSagadin approved these changes

2024-08-27 07:38 UTC, merged